# Generated by Django 4.2.2 on 2023-07-04 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="post",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(verbose_name="Основной текст"),
        ),
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создание"),
        ),
        migrations.AlterField(
            model_name="post",
            name="publish",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата публикаций"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                max_length=250, unique_for_date="publish", verbose_name="url"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("ЧН", "Черновик"), ("ОБ", "Опубликован")],
                default="ЧН",
                max_length=2,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=250, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
